const constants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_REQUEST_SUCCESS: "SIGNUP_REQUEST_SUCCESS",
  SIGNUP_REQUEST_ERROR: "SIGNUP_REQUEST_ERROR",
  SIGNUP_FORM_DATA: "SIGNUP_FORM_DATA"
};
export default constants;