const constants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_REQUEST_SUCCESS: "SIGNUP_REQUEST_SUCCESS",
  SIGNUP_REQUEST_ERROR: "SIGNUP_REQUEST_ERROR",
  SIGNUP_FORM_DATA: "SIGNUP_FORM_DATA",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",
  LOGIN_FORM_DATA: "LOGIN_FORM_DATA",

  ADD_OPTIONS: "ADD_OPTIONS",
  DELETE_OPTIONS: "DELETE_OPTIONS",
  POLL_FORM_DATA: "POLL_FORM_DATA",
  POLL_FORM_REQUEST: "POLL_FORM_REQUEST",
  POLL_FORM_REQUEST_SUCCESS: "POLL_FORM_REQUEST_SUCCESS",
  POLL_FORM_REQUEST_ERROR: "POLL_FORM_REQUEST_ERROR"
};
export default constants;
