const constants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_REQUEST_SUCCESS: "SIGNUP_REQUEST_SUCCESS",
  SIGNUP_REQUEST_ERROR: "SIGNUP_REQUEST_ERROR",
  SIGNUP_FORM_DATA: "SIGNUP_FORM_DATA",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS",
  LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR",
  LOGIN_FORM_DATA: "LOGIN_FORM_DATA",

  LIST_USER_REQUEST: "LIST_USER_REQUEST",
  LIST_USER_REQUEST_SUCCESS: "LIST_USER_REQUEST_SUCCESS",
  LIST_USER_REQUEST_ERROR: "LIST_USER_REQUEST_ERROR",

  LIST_POLLS_REQUEST: "LIST_POLLS_REQUEST",
  LIST_POLLS_REQUEST_SUCCESS: "LIST_POLLS_REQUEST_SUCCESS",
  LIST_POLLS_REQUEST_ERROR: "LIST_POLLS_REQUEST_ERROR",

  DELETE_OPTION_REQUEST: "DELETE_OPTION_REQUEST",
  DELETE_OPTION_REQUEST_SUCCESS: "DELETE_OPTION_REQUEST_SUCCESS",
  DELETE_OPTION_REQUEST_ERROR: "DELETE_OPTION_REQUEST_ERROR"
};
export default constants;
